-- 코드를 입력하세요
SELECT REST_REVIEW.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, round(avg(REVIEW_SCORE),2) SCORE
FROM REST_REVIEW, REST_INFO
WHERE REST_REVIEW.REST_ID = REST_INFO.REST_ID and ADDRESS like '서울%'
GROUP BY REST_INFO.REST_NAME
ORDER BY SCORE desc, FAVORITES desc;