-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_CODE,OFFLINE_SALE.SALES_AMOUNT * PRODUCT.PRICE SALES 
FROM OFFLINE_SALE, PRODUCT 
WHERE OFFLINE_SALE.PRODUCT_ID =  PRODUCT.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_CODE
ORDER BY SALES desc ,PRODUCT_CODE asc;