-- 코드를 입력하세요
SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME,date_format(BOOK.PUBLISHED_DATE,'%Y-%m-%d')
FROM AUTHOR, BOOK
WHERE  (AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID) and BOOK.CATEGORY = '경제'

ORDER BY BOOK.PUBLISHED_DATE asc;